name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Enter Foundry folder
        run: cd foundry

      - name: Install deps
        run: cd foundry && forge install

      - name: Check gas snapshots
        run: cd foundry && forge snapshot --check

      - name: Run tests
        run: cd foundry && forge test --ffi