name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Enter Foundry folder
        run: cd foundry

      - name: Install deps
        run: cd foundry && forge install

      - name: Check gas snapshots
        run: cd foundry && forge snapshot --check --ffi

      - name: Run tests
        run: cd foundry && forge test --ffi
  build-front-end:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.15.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: Run CI command
              run: cd front-end && yarn install --frozen-lockfile


            - name: Check linting
              run: cd front-end && yarn lint
            
            # - name: Run the tests
            #   run: yarn test

            - name: Build
              run: cd front-end && yarn build